### ISSUE TITLE
Cannot read property 'addLayer' of undefined

### ISSUE THREAD

**Issue by FarhAnAbuBakar** [Asymmetrik/angular2-leaflet-draw#14]
hi, i have build my application using electron.
Ive followed the directions on the README and am trying to drop your demo module into my existing app
Im getting the following error:

Error: Error in app/components/leaflet/leafmap/core/core.html:0:81 caused by: Cannot read property 'addLayer' of undefined..

when i remove "LeafletDrawModule" from my root module its running well without toolbar just map.. whem put "LeafletDrawModule"  i encounter this error

any suggestion what i should do to fix this error?

![image](https://cloud.githubusercontent.com/assets/22883899/24418172/b23e359c-141d-11e7-9736-416679d2048f.png)
.

**Comment by FarhAnAbuBakar** [comment]
leaflet-draw.directive.ts

![image](https://cloud.githubusercontent.com/assets/22883899/24418722/7b264584-141f-11e7-92c1-60dfa8480b12.png)

app.module.ts

![image](https://cloud.githubusercontent.com/assets/22883899/24418791/beafa7c8-141f-11e7-9bcc-3bc43bde1a1a.png)

leaflet repository
the code exactly like yours

![image](https://cloud.githubusercontent.com/assets/22883899/24418840/ec294f24-141f-11e7-94d3-78afb9012b6c.png)

**Comment by reblace** [comment]
Can you paste the relevant part of your template and component?

**Comment by reblace** [comment]
Here's an ng cli example:

**npm installs**
```
npm install leaflet leaflet-draw @asymmetrik/angular2-leaflet @asymmetrik/angular2-leaflet-draw
npm install @types/leaflet @types/leaflet-draw
```

**app.module.ts:**
In here, you need to load the two modules
``` js
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
**import { LeafletModule } from '@asymmetrik/angular2-leaflet';**
**import { LeafletDrawModule } from '@asymmetrik/angular2-leaflet-draw';**

import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    **LeafletModule,**
    **LeafletDrawModule**
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

**app.component.ts**
In here you need to load leaflet and leaflet-draw
```
import { Component } from '@angular/core';
**import * as L from 'leaflet';**
**import 'leaflet-draw';**

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  **options = {
    layers: [
      L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 18, attribution: 'Open Street Map' })
    ],
    zoom: 5,
    center: L.latLng({ lat: 46.879966, lng: -121.726909 })
  };

  drawOptions = {
    position: 'topright',
    draw: {
      marker: {
        icon: L.icon({
          iconUrl: '2273e3d8ad9264b7daa5bdbf8e6b47f8.png',
          shadowUrl: '44a526eed258222515aa21eaffd14a96.png'
        })
      },
      polyline: false,
      circle: {
        shapeOptions: {
          color: '#aaaaaa'
        }
      }
    }
  };**
}
```

**app.component.html**
In here you need to add the leafletDraw directive after the leaflet directive and specify options bindings.
```html
<div **leaflet** style="height: 400px;"
     **leafletDraw**
     **[leafletOptions]="options"**
     **[leafletDrawOptions]="drawOptions"**>
</div>
```

.angular-cli.json
This is just showing that you need to load the two css files otherwise it won't render right.
```json
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "project": {
    "name": "my-test"
  },
  "apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": [
        "assets",
        "favicon.ico"
      ],
      "index": "index.html",
      "main": "main.ts",
      "polyfills": "polyfills.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.app.json",
      "testTsconfig": "tsconfig.spec.json",
      "prefix": "app",
      "styles": [
        "styles.css",
        **"../node_modules/leaflet/dist/leaflet.css",**
        **"../node_modules/leaflet-draw/dist/leaflet.draw.css"**
      ],
      "scripts": [],
      "environmentSource": "environments/environment.ts",
      "environments": {
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
    }
  ],
  "e2e": {
    "protractor": {
      "config": "./protractor.conf.js"
    }
  },
  "lint": [
    {
      "project": "src/tsconfig.app.json"
    },
    {
      "project": "src/tsconfig.spec.json"
    },
    {
      "project": "e2e/tsconfig.e2e.json"
    }
  ],
  "test": {
    "karma": {
      "config": "./karma.conf.js"
    }
  },
  "defaults": {
    "styleExt": "css",
    "component": {}
  }
}
```

**Comment by FarhAnAbuBakar** [comment]
here my code

**core.component.ts**
`import { Component, OnInit  } from '@angular/core';

import * as L from 'leaflet';

@Component({
  selector: 'core',
  templateUrl: './app/components/leaflet/leafmap/core/core.html',
  styleUrls: [ './app/components/test/test.component.css' ]

})
export class CoreComponent implements OnInit {

  ngOnInit(): void {
    console.log('core component');
  }

  options = {
		layers: [
			L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 18, attribution: 'Open Street Map' })
		],
		zoom: 5,
		center: L.latLng({ lat: 46.879966, lng: -121.726909 })
	};

  drawOptions = {
		position: 'topright',
		draw: {
			marker: {
				icon: L.icon({
					iconUrl: '2273e3d8ad9264b7daa5bdbf8e6b47f8.png',
					shadowUrl: '44a526eed258222515aa21eaffd14a96.png'
				})
			}
		}
	};
}
`

**core.html**
`<div leaflet style="height: 400px;"
			     leafletDraw
			     [leafletOptions]="options"
			     [leafletDrawOptions]="drawOptions">
</div>
`

**leafmap.componen.ts**
`import { Component, OnInit  } from '@angular/core';

@Component({
  selector: 'leafmap',
  templateUrl: './app/components/leaflet/leafmap/leafmap.html',
  styleUrls: [ './app/components/test/test.component.css' ]

})
export class LeafmapComponent implements OnInit {
  showDemo = false;

  ngOnInit(): void {
    console.log('leafmap component');

    // Primarily for debugging
		setTimeout(() => {
			this.showDemo = true;
		}, 1000);
  }
}
`

**leafmap.html**
`<core></core>
`

**leaflet.component.ts**
`import { Component, OnInit  } from '@angular/core';

@Component({
  selector: 'leaflet',
  templateUrl: './app/components/leaflet/leaflet.html',
  styleUrls: [ './app/components/test/test.component.css' ]

})
export class LeafletComponent implements OnInit {


  ngOnInit(): void {
    console.log('leaflet component');
  }
}
`

**leaflet.html**
`<leafmap></leafmap>
`

**app.module.ts**
`import { NgModule, NO_ERRORS_SCHEMA } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { NgxDatatableModule } from '@swimlane/ngx-datatable';
import { LocationStrategy, HashLocationStrategy } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import { AppComponent } from './app.component';
import { HomeComponent } from './components/home/home.component';
import { SurveyComponent } from './components/survey/survey.component';
import { BffbComponent } from './components/survey/bffb/bffb.component';
import { BfComponent } from './components/survey/bf/bf.component';
import { SpComponent } from './components/survey/sp/sp.component';
import { FdownloadComponent } from './components/file/fdownload/fdownload.component';
import { Fdownload2Component } from './components/file/fdownload2/fdownload2.component';
import { TestComponent } from './components/test/test.component';
import { LoginComponent } from './components/login/login.component';
import { MapsComponent } from './components/maps/maps.component';
import { SummaryComponent } from './components/summary/summary.component';
import { AppRoutingModule } from './app.routing';
// import {DataTableModule} from "angular2-datatable";
import { FileComponent } from './components/file/file.component';
import { PlanningComponent } from './components/planning/planning.component';
import { ToolsComponent } from './components/tools/tools.component';
import { WebcamComponent } from './components/webcam/webcam.component';
import { CameraComponent } from './components/tools/camera/camera.component';

import { LeafletComponent } from './components/leaflet/leaflet.component';
import { LeafmapComponent } from './components/leaflet/leafmap/leafmap.component';
import { CoreComponent } from './components/leaflet/leafmap/core/core.component';
import { LeafletDrawModule } from './components/modules/leaflet-draw.module';
import { LeafletModule } from './components/leaflet-module/leaflet.module';
import { MaterialModule } from '@angular/material';
import 'hammerjs';

@NgModule({
  imports: [
    BrowserModule,
    NgxDatatableModule,
    AppRoutingModule,
    FormsModule,
    ReactiveFormsModule,
    HttpModule,
    MaterialModule.forRoot(),
    LeafletDrawModule.forRoot(),
    LeafletModule.forRoot(),
  ],
  declarations: [


    LeafletComponent,
    LeafmapComponent,
    CoreComponent,

    AppComponent,
    HomeComponent,
    LoginComponent,
    TestComponent,
    MapsComponent,
    SurveyComponent,
    BffbComponent,
    BfComponent,
    SpComponent,
    SummaryComponent,
    FileComponent,
    PlanningComponent,
    ToolsComponent,
    WebcamComponent,
    CameraComponent,
    FdownloadComponent,
    Fdownload2Component,

    LeafletComponent,
    LeafmapComponent,
    CoreComponent,
  ],
  providers: [{provide: LocationStrategy, useClass: HashLocationStrategy}],
  bootstrap: [AppComponent],
  schemas:      [ NO_ERRORS_SCHEMA ]
})
export class AppModule { }
`

here my routing 

**leaflet-routing.module.ts**
`import { NgModule } from '@angular/core';
import { Routes,
     RouterModule } from '@angular/router';

import {LeafletComponent } from './leaflet.component';

const routes: Routes = [
  {
    path: '',
    component:LeafletComponent, data: {
      title: 'Webcam' }
  },

];

@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule]
})
export class LeafletRoutingModule {}
`

**app-routing.ts**
`import { NgModule }       from '@angular/core';
import { Routes,
         RouterModule } from '@angular/router';
import { HomeComponent } from './components/home/home.component';
import { LoginComponent } from './components/login/login.component';
import { TestComponent } from './components/test/test.component';
import { MapsComponent } from './components/maps/maps.component';
import { SurveyComponent } from './components/survey/survey.component';
import { BffbComponent } from './components/survey/bffb/bffb.component';
import { BfComponent } from './components/survey/bf/bf.component';
import { SpComponent } from './components/survey/sp/sp.component';
import { SummaryComponent } from './components/summary/summary.component';
import { PlanningComponent } from './components/planning/planning.component';
import { FileComponent } from './components/file/file.component';
import { ToolsComponent } from './components/tools/tools.component';
import { WebcamComponent } from './components/webcam/webcam.component';
import { FdownloadComponent } from './components/file/fdownload/fdownload.component';
import { Fdownload2Component } from './components/file/fdownload2/fdownload2.component';
import { LeafletComponent } from './components/leaflet/leaflet.component';

export const routes: Routes = [
  { path: '', redirectTo: '/test', pathMatch: 'full'},
  { path: 'home', component: HomeComponent },
  { path: 'login', component: LoginComponent },
  { path: 'maps', component: MapsComponent },
  { path: 'survey', component: SurveyComponent },
  { path: 'bffb', component: BffbComponent },
  { path: 'bf', component: BfComponent },
  { path: 'sp', component: SpComponent },
  { path: 'summary', component: SummaryComponent },
  { path: 'file', component: FileComponent },
  { path: 'planning', component: PlanningComponent },
  { path: 'test', component: TestComponent },
  { path: 'tools', component: ToolsComponent },
  { path: 'webcam', component: WebcamComponent },
  { path: 'fdownload', component: FdownloadComponent },
  { path: 'fdownload2', component: Fdownload2Component },
  { path: 'leaflet', component: LeafletComponent },

];
@NgModule({
  imports: [ RouterModule.forRoot(routes) ],
  exports: [ RouterModule ]
})
export class AppRoutingModule {}
`

**index.html**
in index.html i already import those css like said...but the error still appear
`<!DOCTYPE html>
<html lang="en">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>iFOSField - Field Work Applications</title>
    <link href="../node_modules/material-components-web/dist/material-components-web.css" rel="stylesheet">
    <link href="../node_modules/@angular/material/core/theming/prebuilt/indigo-pink.css" rel="stylesheet">
    <link href="../node_modules/material-design-icons/iconfont/material-icons.css" rel="stylesheet" >
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.0.3/dist/leaflet.css" />
    <link href="../node_modules/@swimlane/ngx-datatable/release/index.css" rel="stylesheet" >
    <link href="../node_modules/@swimlane/ngx-datatable/release/themes/material.css" rel="stylesheet" >
    <link href="../node_modules/@swimlane/ngx-datatable/release/assets/icons.css" rel="stylesheet" >
    <link href="../node_modules/leaflet/dist/leaflet.css" rel="stylesheet" >
    <link href="../node_modules/leaflet-draw/dist/leaflet.draw.cs" rel="stylesheet" >
    <link rel="stylesheet" href="loading-bars.css" />

    <style>
    html, body {
      margin: 0;
      width: 100%;
      height: 100%;
    }
    </style>
  </head>
  <body style="overflow: hidden; background-color: rgba(0,0,0,0); margin: 0" >
    <App>
      
      <div class="splash">
          <div class="color-line"></div>
              <div class="splash-title">
                  <h1>IFOSField</h1>
                  <img src="loading-bars.svg" width="64" height="64" />
              </div>
          </div>
    </App>
  </body>
  <script src="../node_modules/material-components-web/dist/material-components-web.js"></script>
  <script src="../node_modules/reflect-metadata/Reflect.js"></script>
  <script src="bootstrap.ts"></script>
</html>
`
 
**error**
![image](https://cloud.githubusercontent.com/assets/22883899/24444582/6fcbccc0-1499-11e7-9a83-eccf512526e3.png)

**Comment by FarhAnAbuBakar** [comment]
here is my code 

**core.component.ts**
in this file im already imported leaflet and leaflet-draw file

```javascript
import { Component, OnInit  } from '@angular/core';

import * as L from 'leaflet';

import 'leaflet-draw';

@Component({
  selector: 'core',
  templateUrl: './app/components/leaflet/leafmap/core/core.html',
  styleUrls: [ './app/components/test/test.component.css' ]

})
export class CoreComponent implements OnInit {

  ngOnInit(): void {
    console.log('core component');
  }

  options = {
		layers: [
			L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 18, attribution: 'Open Street Map' })
		],
		zoom: 5,
		center: L.latLng({ lat: 46.879966, lng: -121.726909 })
	};

  drawOptions = {
		position: 'topright',
		draw: {
			marker: {
				icon: L.icon({
					iconUrl: '2273e3d8ad9264b7daa5bdbf8e6b47f8.png',
					shadowUrl: '44a526eed258222515aa21eaffd14a96.png'
				})
			}
		}
	};
}
```

**core.html**
```javascript
<div leaflet style="height: 400px;"
			     leafletDraw
			     [leafletOptions]="options"
			     [leafletDrawOptions]="drawOptions">
</div>
```

**leafmap.component.ts**
```javascript
  import { Component, OnInit  } from '@angular/core';

  @Component({
    selector: 'leafmap',
    templateUrl: './app/components/leaflet/leafmap/leafmap.html',
    styleUrls: [ './app/components/test/test.component.css' ]

  })
  export class LeafmapComponent implements OnInit {
    showDemo = false;

    ngOnInit(): void {
      console.log('leafmap component');

      // Primarily for debugging
  		setTimeout(() => {
  			this.showDemo = true;
  		}, 1000);
    }
  }

```

**leafmap.html**
```javascript
<core></core>
```

**leaflet.component.ts**
```javascript
import { Component, OnInit  } from '@angular/core';

@Component({
  selector: 'leaflet',
  templateUrl: './app/components/leaflet/leaflet.html',
  styleUrls: [ './app/components/test/test.component.css' ]

})
export class LeafletComponent implements OnInit {


  ngOnInit(): void {
    console.log('leaflet component');
  }
}
```

**leaflet.html**
```javascript
<leafmap></leafmap>
```

**app.module.ts**
in here i already load leafletmodule and leafletDrawmodule
```javascript
import { NgModule, NO_ERRORS_SCHEMA } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { NgxDatatableModule } from '@swimlane/ngx-datatable';
import { LocationStrategy, HashLocationStrategy } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import { AppComponent } from './app.component';
import { HomeComponent } from './components/home/home.component';
import { SurveyComponent } from './components/survey/survey.component';
import { BffbComponent } from './components/survey/bffb/bffb.component';
import { BfComponent } from './components/survey/bf/bf.component';
import { SpComponent } from './components/survey/sp/sp.component';
import { FdownloadComponent } from './components/file/fdownload/fdownload.component';
import { Fdownload2Component } from './components/file/fdownload2/fdownload2.component';
import { TestComponent } from './components/test/test.component';
import { LoginComponent } from './components/login/login.component';
import { MapsComponent } from './components/maps/maps.component';
import { SummaryComponent } from './components/summary/summary.component';
import { AppRoutingModule } from './app.routing';
// import {DataTableModule} from "angular2-datatable";
import { FileComponent } from './components/file/file.component';
import { PlanningComponent } from './components/planning/planning.component';
import { ToolsComponent } from './components/tools/tools.component';
import { WebcamComponent } from './components/webcam/webcam.component';
import { CameraComponent } from './components/tools/camera/camera.component';

import { LeafletComponent } from './components/leaflet/leaflet.component';
import { LeafmapComponent } from './components/leaflet/leafmap/leafmap.component';
import { CoreComponent } from './components/leaflet/leafmap/core/core.component';
import { LeafletDrawModule } from './components/modules/leaflet-draw.module';
import { LeafletModule } from './components/leaflet-module/leaflet.module';
import { MaterialModule } from '@angular/material';
import 'hammerjs';

@NgModule({
  imports: [
    BrowserModule,
    NgxDatatableModule,
    AppRoutingModule,
    FormsModule,
    ReactiveFormsModule,
    HttpModule,
    MaterialModule.forRoot(),
    LeafletDrawModule.forRoot(),
    LeafletModule.forRoot(),
  ],
  declarations: [


    LeafletComponent,
    LeafmapComponent,
    CoreComponent,

    AppComponent,
    HomeComponent,
    LoginComponent,
    TestComponent,
    MapsComponent,
    SurveyComponent,
    BffbComponent,
    BfComponent,
    SpComponent,
    SummaryComponent,
    FileComponent,
    PlanningComponent,
    ToolsComponent,
    WebcamComponent,
    CameraComponent,
    FdownloadComponent,
    Fdownload2Component,

    LeafletComponent,
    LeafmapComponent,
    CoreComponent,
  ],
  providers: [{provide: LocationStrategy, useClass: HashLocationStrategy}],
  bootstrap: [AppComponent],
  schemas:      [ NO_ERRORS_SCHEMA ]
})
export class AppModule { }
```

here is my routing code
**leaflet-routing.module.ts**
```javascript
import { NgModule } from '@angular/core';
import { Routes,
     RouterModule } from '@angular/router';

import {LeafletComponent } from './leaflet.component';

const routes: Routes = [
  {
    path: '',
    component:LeafletComponent, data: {
      title: 'Webcam' }
  },

];

@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule]
})
export class LeafletRoutingModule {}
```

**app-routing.ts**
```javascript
import { NgModule }       from '@angular/core';
import { Routes,
         RouterModule } from '@angular/router';
import { HomeComponent } from './components/home/home.component';
import { LoginComponent } from './components/login/login.component';
import { TestComponent } from './components/test/test.component';
import { MapsComponent } from './components/maps/maps.component';
import { SurveyComponent } from './components/survey/survey.component';
import { BffbComponent } from './components/survey/bffb/bffb.component';
import { BfComponent } from './components/survey/bf/bf.component';
import { SpComponent } from './components/survey/sp/sp.component';
import { SummaryComponent } from './components/summary/summary.component';
import { PlanningComponent } from './components/planning/planning.component';
import { FileComponent } from './components/file/file.component';
import { ToolsComponent } from './components/tools/tools.component';
import { WebcamComponent } from './components/webcam/webcam.component';
import { FdownloadComponent } from './components/file/fdownload/fdownload.component';
import { Fdownload2Component } from './components/file/fdownload2/fdownload2.component';
import { LeafletComponent } from './components/leaflet/leaflet.component';

export const routes: Routes = [
  { path: '', redirectTo: '/test', pathMatch: 'full'},
  { path: 'home', component: HomeComponent },
  { path: 'login', component: LoginComponent },
  { path: 'maps', component: MapsComponent },
  { path: 'survey', component: SurveyComponent },
  { path: 'bffb', component: BffbComponent },
  { path: 'bf', component: BfComponent },
  { path: 'sp', component: SpComponent },
  { path: 'summary', component: SummaryComponent },
  { path: 'file', component: FileComponent },
  { path: 'planning', component: PlanningComponent },
  { path: 'test', component: TestComponent },
  { path: 'tools', component: ToolsComponent },
  { path: 'webcam', component: WebcamComponent },
  { path: 'fdownload', component: FdownloadComponent },
  { path: 'fdownload2', component: Fdownload2Component },
  { path: 'leaflet', component: LeafletComponent },

];
@NgModule({
  imports: [ RouterModule.forRoot(routes) ],
  exports: [ RouterModule ]
})
export class AppRoutingModule {}
```

**index.html**
i already import leaflet and leaflet draw css in this file
```javascript
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>iFOSField - Field Work Applications</title>
    <link href="../node_modules/material-components-web/dist/material-components-web.css" rel="stylesheet">
    <link href="../node_modules/@angular/material/core/theming/prebuilt/indigo-pink.css" rel="stylesheet">
    <link href="../node_modules/material-design-icons/iconfont/material-icons.css" rel="stylesheet" >
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.0.3/dist/leaflet.css" />
    <link href="../node_modules/@swimlane/ngx-datatable/release/index.css" rel="stylesheet" >
    <link href="../node_modules/@swimlane/ngx-datatable/release/themes/material.css" rel="stylesheet" >
    <link href="../node_modules/@swimlane/ngx-datatable/release/assets/icons.css" rel="stylesheet" >
    <link href="../node_modules/leaflet/dist/leaflet.css" rel="stylesheet" >
    <link href="../node_modules/leaflet-draw/dist/leaflet.draw.cs" rel="stylesheet" >
    <link rel="stylesheet" href="loading-bars.css" />

    <style>
    html, body {
      margin: 0;
      width: 100%;
      height: 100%;
    }
    </style>
  </head>
  <body style="overflow: hidden; background-color: rgba(0,0,0,0); margin: 0" >
    <App>
      <!-- Show simple splash screen-->
      <div class="splash">
          <div class="color-line"></div>
              <div class="splash-title">
                  <h1>IFOSField</h1>
                  <img src="loading-bars.svg" width="64" height="64" />
              </div>
          </div>
    </App>
  </body>
  <script src="../node_modules/material-components-web/dist/material-components-web.js"></script>
  <script src="../node_modules/reflect-metadata/Reflect.js"></script>
  <script src="bootstrap.ts"></script>
</html>
```

i already done like u said i that error still appear

![image](https://cloud.githubusercontent.com/assets/22883899/24447818/cdd8eb76-14a4-11e7-8b29-7db2ebee4ade.png)

**Comment by FarhAnAbuBakar** [comment]
when i remove leafletDrawmodule from app.module.ts a map working well but the draw toolbar dont appear

![image](https://cloud.githubusercontent.com/assets/22883899/24449508/056ccf80-14aa-11e7-98ad-601107cd542d.png)

**Comment by reblace** [comment]
Something that might be causing issues is that you are declaring leaflet.component.ts with a selector 'leaflet' that will collide with the selector for the leaflet directive.

If that's the case, it's possible that your leaflet component is getting loaded on the core.html div and then the leaflet directive that is getting injected into the leafletDraw component is not initialized, which would lead to the error you're getting.

Try changing the selector of your leaflet.component.ts from 'leaflet' to something else and see if that makes a difference.

**Comment by FarhAnAbuBakar** [comment]
**laeflet.component.ts**
```javascript
import { Component, OnInit  } from '@angular/core';

@Component({
  selector: 'app-component',
  templateUrl: './app/components/leaflet/leaflet.html',
  styleUrls: [ './app/components/test/test.component.css' ]

})
export class LeafletComponent implements OnInit {


  ngOnInit(): void {
    console.log('leaflet component');
  }

}
```

i already change the selector from leaflet to app-component but the error still there... Cannot read property 'addLayer' of undefined

**Comment by reblace** [comment]
Is there any way you could send me an example that reproduces the problem?

**Comment by FarhAnAbuBakar** [comment]
error fixed... i use this code and my leaflet-draw worked now

```javascript
var drawnItems = L.featureGroup();
        map.addLayer(drawnItems);

var options = {
        position: 'topright',
        draw: {
            polyline: {
                shapeOptions: {
                    color: '#f357a1',
                    weight: 10
                }
            },
            polygon: {
                allowIntersection: false, // Restricts shapes to simple polygons
                drawError: {
                    color: '#e1e100', // Color the shape will turn when intersects
                    message: '<strong>Oh snap!<strong> you can\'t draw that!' // Message that will show when intersect
                },
                shapeOptions: {
                    color: '#bada55'
                }
            },
            circle: false, // Turns off this drawing tool
            rectangle: {
                shapeOptions: {
                    clickable: false
                }
            },
        },
        edit: {
            featureGroup: drawnItems
        }
    };

var drawControl = new L.Control.Draw(options);
        map.addControl(drawControl);

        map.on(L.Draw.Event.CREATED, function(e:any) {
            var layer = e.layer;

            drawnItems.addLayer(layer);
        });
```

**Comment by reblace** [comment]
User got it working.
