### ISSUE TITLE
How to use without the Draw Toolbar UI?

### ISSUE THREAD

**Issue by mickeyjohn** [Asymmetrik/angular2-leaflet-draw#20]
It works for me when using options with Toolbar UI. However, I am having type errors problem when trying to use without its Toolbar UI. When trying something like:
```
import * as L from 'leaflet';
import 'leaflet-draw';
declare var Draw: any;

buttonClick() {
    this.polygonDrawer = new Draw.Polygon(); << error
    this.polygonDrawer.enable();
}
```

error:
ERROR Error: Uncaught (in promise): ReferenceError: Draw is not defined
ReferenceError: Draw is not defined
....
Any pointer on what was wrong with this way? Thanks a lot.

**Comment by reblace** [comment]
A couple things are going on here:

1. I don't think the leaflet-draw typings (https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/leaflet-draw/index.d.ts) expose the internal classes used by the UI. This isn't really an issue (as you're showing by declaring ```Draw```.

2. ```Polygon``` is actually located in ```L.Draw.Polygon``` (https://github.com/Leaflet/Leaflet.draw/blob/master/src/draw/handler/Draw.Polygon.js).


You have a few options to try to fix this:
- You can submit a PR to add the missing class specifications for the various shapes to DefiniatelyTyped
- You can write your own local types file and explicitly reference it or add it to the types list in your tsconfig
- You can cast L to any and then just do whatever you want ```var _L = L as any;```


Alternatively, if you're really not using the toolbar, you should be able to add shapes that can be edited by just adding them programmatically to the feature group layer.
Eg:

```
...
var shapeOptions = {
	stroke: true,
	color: '#f06eaa',
	weight: 4,
	opacity: 0.5,
	fill: true,
	fillColor: null, //same as color by default
	fillOpacity: 0.2,
	clickable: true,
	editable: true
};
var poly = new L.Polygon(latlngs, this.options.shapeOptions);
featureGroup.addLayer({ type: 'polygon', layer: poly });
...
```

I think that should work.

**Comment by mickeyjohn** [comment]
Thanks for your quick help. I am new to TypeScript so only can try options with _L and alternative way. with _L I still got error when trying: 
`this.polygonDrawer = new _L.Draw.Polygon();`
error:
core.es5.js:1084 ERROR Error: Uncaught (in promise): TypeError: Cannot read property '_container' of undefined

error:
Argument of type '{ type: string; layer: Polygon; }' is not assignable to parameter of type 'Layer'.
  Object literal may only specify known properties, and 'type' does not exist in type 'Layer'

with this line:
`featureGroup.addLayer({ type: 'polygon', layer: poly });`

featureGroup: L.FeatureGroup

I wonder why do we have so may problems with typing stuff. Can we use pure JavaScript libraries in TypeScript Angular 2 app normally?

**Comment by reblace** [comment]
The first error is cause you need to pass in the map as a parameter to L.Draw.Polygon, eg. ```new _L.Draw.Polygon(map)```.
See (https://github.com/Leaflet/Leaflet.draw/blob/master/src/draw/DrawToolbar.js) as a reference.

The second error I think is cause I made a mistake in my example. I corrected it above, the change was to modify this:

```
featureGroup.addLayer({ type: 'polygon', layer: poly });
```
to this:
```
featureGroup.addLayer(poly);
```

**Comment by mickeyjohn** [comment]
I got it. It works now. I need to learn more myself and from you guys. I really your help. :)
