### ISSUE TITLE
save leaflet map with drawing as png/jpg

### ISSUE THREAD

**Issue by FarhAnAbuBakar** [Asymmetrik/angular2-leaflet-draw#21]
hi..

any ideas how to save map as png/jpg after i draw polygon, polyline and marker.. what function i need to use..

thanks

**Comment by reblace** [comment]
I don't know. I'm not sure leaflet draw supports that. There may be some other plugin that could do that for you, but you'd have to go look to see what/if anything is supported. If there is some specific functionality in leaflet-draw that does allow you to do this, there's nothing in this component that should prevent you from utilizing it.
