### ISSUE TITLE
remove drawn rectangle

### ISSUE THREAD

**Issue by deniskkk** [Asymmetrik/angular2-leaflet-draw#26]
how can i remove drawn rectangle? I want to draw rectangle then select all items inside it and remove rectangle from map. I can catch the `map.on('draw:created', this.onDrawRect.bind(this));` Im on typescript;

**Comment by reblace** [comment]
Right now the way the plugin is set up, you'll need to manually remove the layer from the map. Easiest way to do this would be to pass in your own featureGroup to the options for the draw plugin and then call ```clearLayers()``` on that group when you want to clear the rectangle. That will remove all of the drawn objects from the map.

The plugin is currently pretty lightweight, so it doesn't support a cleaner way to do this at this time.
