### ISSUE TITLE
Removing Draw control programmatically from map instance

### ISSUE THREAD

**Issue by K0ntrol** [Asymmetrik/angular2-leaflet-draw#28]
Is it possible to remove the draw control by clicking a UI button in my map component outside the map instance?

I know this would be possible by using `this.map.removeControl(this.drawControl)` if draw control was added to the map via `this.map.addControl(this.drawControl)`

**Comment by reblace** [comment]
I just published a new version that removes the control on destroy. You should be able to do something like the following:

```
<button class="btn btn-default" (click)="shown = !shown">Show/Hide Control</button>
<div leaflet style="height: 400px;" [leafletOptions]="options">
	<div *ngIf="shown" leafletDraw [leafletDrawOptions]="drawOptions"></div>
</div>
```

The idea there is that you have the draw control on a nested element which you can use ngIf to add/remove from the DOM. When it gets removed (ngIf false), it will remove the control from the map. When it gets added (ngIf true), it will add the control to the map.

**Comment by reblace** [comment]
Added some details in README and updated plugin to deal with add/remove control on add/remove dom element.
